from jb_game.jb_dev_car_incident_event import CarIncident
from jb_game.jb_dev_random_events import RandomEvents
from jb_game.jb_dev_stats import JBStats
from jb_dev_day_cycle import DayCycle
from jb_dev_game import Game
from jb_game.jb_dev_story import Story


def main():
    stats = JBStats()
    day_cycle = DayCycle()
    events_list = RandomEvents()
    game = Game(stats, day_cycle, events_list)

    story = Story(stats)
    story.start_game_message()

    game.set_difficulty_level()

    CarIncident.car_incident_event(stats)

    game.main_menu()


if __name__ == "__main__":
    main()


# 25.11.2025 - State of the game.

# DONE:

# CAR INCIDENT EVENT, MULTIPLE DECISIONS.
# 20-30 MINS OF GAMEPLAY
# 3 FULLY WORKING STATS: CODING, MONEY, HATRED
# 100 CODING CHECK
# DAYS CALCULATOR
# GAME MENU:
# 1. SELECT ACTIVITY (ONLY ONE ACTIVITY DAILY: 1. GYM, 2. READ, 3. STUDY PYTHON, 4. BOUNCER NIGHT SHIFT)
# 2. STATS REPORT
# 5. END THE DAY.
# RANDOM EVENTS WORKING: 7 RANDOM EVENTS
# DAY CYCLE FULLY WORKING.
# DEBUFFS AND BUFFS

# TO BE DONE:

# HIGH PRIORITY:

# STATS - 0 MONEY BACKGROUND CHECK, 100 HATRED BACKGROUND CHECK
# DAY24 - MM LUNCH EVENT - GOOD/NEUTRAL/BAD ENDING - NO RNG, ONLY YOUR CHOICES, OPTIONS BASED ON PREREQUIREMENTS
# (1. DO YOU HAVE ENOUGH MONEY TO LEAVE NOW? "HELL YEAH (>100k, +2MM POINTS, >50k, +1MM POINTS)" ETC...)...POSSIBLE OUTCOMES:
# (2. HOW MUCH DO YOU ACTUALLY HATE POLICE NOW? (>75, 2+MM POINTS, >30, 1+MM POINTS) ETC...
# (3. HOW MUCH DO YOU KNOW ABOUT CODING NOW? (>75, 2+MM POINTS, > 50, 1+MM POINTS) ETC...
# (4. HOW YOU APPROACH THE MEETING (1. PAY FOR THE LUNCH, BUY NEW CLOTHES -2500, 2+MM POINTS, 2. COME IN CASUAL
# CLOTHES)
# (5. WHAT YOU TALK ABOUT: (1. TALK ABOUT HIM +2MM POINTS, 2. SHOW HIM YOUR CODING KNOWLEDGE +25 CODING SKILLS,
# 3. RANT ABOUT HOW YOU HATE YOUR JOB - 50 PCR HATRED
# GOOD - FULL SUPPORT FROM MM - 50% STAT INCREASE, -30 PCR HATRED
# NEUTRAL - PARTIAL HELP FROM MM - 25% STAT INCREASE, -15 PCR HATRED
# BAD - NO BONUSES FROM MM
# DAY25-29 - ADD SECRET MENU OPTION AFTER MEETING WITH MM CALLED 'PREPARATION EFFORTS': INCLUDES WAYS TO COMBAT
#THE COLONEL WITH MONEY, HATRED AND CODING SKILLS (WILL GIVE YOU BUFFS AND NEW OPTIONS AT DAY30)
# DAY30 - COLONEL ARRIVES EVENT - ...
# FIX BETTER CALL PAUL EVENT


# MEDIUM PRIORITY:

# PERKS GAINED AFTER DOING ANY ACTIVITY X TIMES (I.E. BRAWLER - GO TO GYM 10 TIMES...)
# PERKS WILL ALLOW SECRET OPTIONS IN THE LAST MAIN EVENT OF THE GAME.

# LOW PRIORITY:

# ADD NIGHTMARE DIFFICULTY
# PS EASTER EGG




